# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# настройка для генерации с базой.
services:
  - postgresql

before_install:
  - psql -c 'create database managingPassports;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление, если сборка упала, на почту youremail@smtp.ru(Изменить на свою)
notifications:
  email:
    recipients:
      -dmstrannik@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="de937e6b-3d64-4743-b422-125f1d801d24"